config/routes.rb
FourthAndInches::Application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations" }

  root 'home#index'
  get 'about'     => 'home#about',     as: 'about'
  get 'contact'   => 'home#contact',   as: 'contact'
  get 'dashboard' => 'dashboard#show', as: 'dashboard'
  get 'faq'       => 'home#faq',       as: 'faq'
  get 'features'  => 'home#features',  as: 'features'

  # Access Codes
  post 'send_access_code' => 'access_codes#send_access_code', as: 'send_access_code'
  get 'access/:id' => 'access_codes#verify_access_code', as: 'verify_access_code'

  get 'coaches_corner' => 'coaches#coaches_corner', as: 'coaches_corner'
  get 'office_manager' => 'office#office_manager',

                                                    as: 'office_manager'
  get 'schedule_manager' => 'schedules#schedule_manager',
                                                    as: 'schedule_manager'
  get 'team_manager' => 'teams#team_manager',       as: 'team_manager'
  get 'team_dashboard/:id' => 'teams#team_dashboard', as: 'team_dashboard'

  # post 'opponents/:id/list_destroy' => 'opponents#list_destroy',  as: 'list_destroy'
  post 'programs/set_fee' => 'programs#set_fee'
  post 'programs/:id/ajax_program_edits' => 'programs#ajax_program_edits'

  get "websites/:id" => 'websites#show', as: 'website'
  get 'all_players' => 'websites#all_players'

  resources :users
  resources :coaches,     only: [:new, :create]
  resources :programs,    except: [:edit]
  resources :websites,    only: :create
  resources :charges
  resources :divisions
  resources :opponents do
    member do
      post :list_destroy
    end
  end



  resources :events,      only: [:index]
  resources :schedules,   except: :index
  resources :dashboard,   only: :create
  resources :players
  resources :teams
  resources :sponsors,    only: [:index]
  resources :inventory,   only: [:index]
  resources :merchandise, only: [:index]
end

app/models/dashboard.rb
# == Schema Information
#
# Table name: dashboards
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Dashboard < ActiveRecord::Base

  belongs_to :user
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  before_action :authenticate_user!
  layout :resolve_layout

  def new
  end

  def show
    # binding.pry
    @user = current_user
  end

  private

  def resolve_layout
    if current_user.has_role? 'master'
      "master"
    elsif current_user.has_role? 'head_coach'
      "application"
    end
  end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  before_action :authenticate_user!

  def show
    @current_user = current_user
  end

end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboard/show.html.haml
- if current_user.has_role?('head_coach')
  .content-container
    .row
      %section#top_third
        .todays_date
          = display_todays_date
        %h3
          = "Welcome coach #{current_user.first_name.capitalize}'s to your dashboard"
    .power-line-separator
    .row#middle_third
      .col-md-3.col-xs-6
        .outer-rink
          = link_to team_manager_path, class: "manager-button" do
            .dash-btn-image
              %i.fa.fa-clipboard.fa-5x
            .link-text team manager

      - unless current_user.teams.blank?
        .col-md-3.col-xs-6
          .outer-rink
            = link_to schedule_manager_path, class: "manager-button" do
              .dash-btn-image
                %i.fa.fa-calendar.fa-5x
              .link-text schedule manager

      .col-md-3.col-xs-6
        .outer-rink
          = link_to office_manager_path, class: "manager-button" do
            .dash-btn-image
              %i.fa.fa-clipboard.fa-5x
            .link-text office manager
      .col-md-3.col-xs-6
        .outer-rink
          = link_to coaches_corner_path, class: "manager-button" do
            .dash-btn-image
              %i.fa.fa-clipboard.fa-5x
            .link-text coaches' corner

    .power-line-separator
    .row
      %section#bottom_third

- elsif current_user.has_role? "master"
  #director-dashboard-ready
    #first_level
    .hi-icon-wrap.hi-icon-effect-8
      / %h3
      /   = link_to 'teams', teams_path, class: 'action-tile'
      / %h3
      /   = link_to 'staff', users_path, class: 'action-tile'
      / %h3
      /   = link_to 'program info', programs_path, class: 'action-tile'
      / %h3
      /   = link_to 'events', events_path, class: 'action-tile'
      / %h3
      /   = link_to 'sponsors', sponsors_path, class: 'action-tile'
      / %h3
      /   = link_to 'merchandising', merchandise_index_path, class: 'action-tile'
      / %h3
      /   = link_to 'inventory', inventory_index_path, class: 'action-tile'
      / %h3
      /   - if current_user.program.nil?
      /     = link_to 'website', dashboard_path, class: 'action-tile'
      /   - else
      /     = link_to 'website', website_path(@website), class: 'action-tile'