config/routes.rb
FourthAndInches::Application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations" }

  root 'home#index'
  get 'about'     => 'home#about',     as: 'about'
  get 'contact'   => 'home#contact',   as: 'contact'
  get 'dashboard' => 'dashboard#show', as: 'dashboard'
  get 'faq'       => 'home#faq',       as: 'faq'
  get 'features'  => 'home#features',  as: 'features'

  # Access Codes
  post 'send_access_code' => 'access_codes#send_access_code', as: 'send_access_code'
  get 'access/:id' => 'access_codes#verify_access_code', as: 'verify_access_code'

  get 'coaches_corner' => 'coaches#coaches_corner', as: 'coaches_corner'
  get 'office_manager' => 'office#office_manager',

                                                    as: 'office_manager'
  get 'schedule_manager' => 'schedules#schedule_manager',
                                                    as: 'schedule_manager'
  get 'team_manager' => 'teams#team_manager',       as: 'team_manager'
  get 'team_dashboard/:id' => 'teams#team_dashboard', as: 'team_dashboard'

  # post 'opponents/:id/list_destroy' => 'opponents#list_destroy',  as: 'list_destroy'
  post 'programs/set_fee' => 'programs#set_fee'
  post 'programs/:id/ajax_program_edits' => 'programs#ajax_program_edits'

  get "websites/:id" => 'websites#show', as: 'website'
  get 'all_players' => 'websites#all_players'

  resources :users
  resources :coaches,     only: [:new, :create]
  resources :programs,    except: [:edit]
  resources :websites,    only: :create
  resources :charges
  resources :divisions
  resources :opponents do
    member do
      post :list_destroy
    end
  end



  resources :events,      only: [:index]
  resources :schedules,   except: :index
  resources :dashboard,   only: :create
  resources :players
  resources :teams
  resources :sponsors,    only: [:index]
  resources :inventory,   only: [:index]
  resources :merchandise, only: [:index]
end

app/models/division.rb
# == Schema Information
#
# Table name: divisions
#
#  id           :integer          not null, primary key
#  name         :string(255)
#  age_group    :string(255)
#  program_id   :integer
#  created_at   :datetime
#  updated_at   :datetime
#  weight_class :string(255)
#

class Division < ActiveRecord::Base
  has_many :teams
  belongs_to :program

  scope :find_teams_divisions, lambda { |div_name|
    where( name: div_name)
   }

end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController

  before_action :find_division, only: [:edit, :update, :destroy]

  def index
    @divisions = get_divisions
  end

  def new
    @division = Division.new
    @program_id = current_user.program.id
    @program = current_user.program.team_name
  end

  def create
    @division = Division.new(division_params)
    @division.program_id = params[:program_id]
    if @division.save
      # if add another button was clicked, go back to page
      if params.has_value? "add more"
        redirect_to :back, notice: 'Please add another division.'
      else
        redirect_to(controller: 'teams', action: 'index')
      end
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @division.update(division_params)
    if @division.save
      redirect_to teams_path, notice: 'division successfully updated'
    else
      render 'edit'
    end
  end

  def destroy
    division = { id: @division.id }
    @division.destroy
    render :json => {status: "ok"}
  end


  private

    def find_division
      @division = Division.find(params[:id])
    end

    def division_params
      params.require(:division).permit(:name, :age_group)
    end


end

app/helpers/divisions_helper.rb
module DivisionsHelper
end

app/views/divisions/edit.html.haml
%div
  = render 'layouts/nav_controls'

  %h1 Edit Divisions

  %ul
  = form_for(@division, url: division_path) do |f|
    %li
      = f.label :name, "What's the name of the division?"
      = f.text_field :name
    %li
      = f.label :age_group, "What's the age group?"
      = f.text_field :age_group
    %li
      = f.label :weight_class, "and the weight class?"
      = f.text_field :weight_class
    %li
      = f.submit

app/views/divisions/index.html.haml
%h1 Divisions#index
%p Find me in app/views/divisions/index.html.haml

- @divisions.each do |div|
  %li
    = div.name

app/views/divisions/new.html.haml
%div
  = render 'layouts/nav_controls'

%header.form-header
  %h1#step2
    %span Add divisions to your program
  = form_for(@division, url: divisions_path, autocomplete: "off", html: {class: 'simform', id: 'theForm'} ) do |f|
    = hidden_field_tag(:program_id, @program_id)
    = hidden_field_tag(:form_name, "add-division")
    .simform-inner
      %ol.questions
        %li
          %span
            = f.label :name, "What's the name of the division?"
          = f.text_field :name, placeholder: 'e.g. 9 Year Olds'
        %li
          %span
            = f.label :age_group, "What's the age group?"
          = f.text_field :age_group, placeholder: 'e.g. 9 or 10 - 11'
        %li
          %span
            = f.label :weight_class, "and the weight class?"
          = f.text_field :weight_class

      .controls
        %button.next.fa.fa-arrow-circle-right.fa-2x
        .progress
        %span.number
          %span.number-current
          %span.number-total
        %span.error-message
        .press_enter_msg
          %span Please press enter
          %em or
          %span
            %i.fa.fa-arrow-circle-right
          %span to continue

    %span.final-message