config/routes.rb
FourthAndInches::Application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations" }

  root 'home#index'
  get 'about'     => 'home#about',     as: 'about'
  get 'contact'   => 'home#contact',   as: 'contact'
  get 'dashboard' => 'dashboard#show', as: 'dashboard'
  get 'faq'       => 'home#faq',       as: 'faq'
  get 'features'  => 'home#features',  as: 'features'

  # Access Codes
  post 'send_access_code' => 'access_codes#send_access_code', as: 'send_access_code'
  get 'access/:id' => 'access_codes#verify_access_code', as: 'verify_access_code'

  get 'coaches_corner' => 'coaches#coaches_corner', as: 'coaches_corner'
  get 'office_manager' => 'office#office_manager',

                                                    as: 'office_manager'
  get 'schedule_manager' => 'schedules#schedule_manager',
                                                    as: 'schedule_manager'
  get 'team_manager' => 'teams#team_manager',       as: 'team_manager'
  get 'team_dashboard/:id' => 'teams#team_dashboard', as: 'team_dashboard'

  # post 'opponents/:id/list_destroy' => 'opponents#list_destroy',  as: 'list_destroy'
  post 'programs/set_fee' => 'programs#set_fee'
  post 'programs/:id/ajax_program_edits' => 'programs#ajax_program_edits'

  get "websites/:id" => 'websites#show', as: 'website'
  get 'all_players' => 'websites#all_players'

  resources :users
  resources :coaches,     only: [:new, :create]
  resources :programs,    except: [:edit]
  resources :websites,    only: :create
  resources :charges
  resources :divisions
  resources :opponents do
    member do
      post :list_destroy
    end
  end



  resources :events,      only: [:index]
  resources :schedules,   except: :index
  resources :dashboard,   only: :create
  resources :players
  resources :teams
  resources :sponsors,    only: [:index]
  resources :inventory,   only: [:index]
  resources :merchandise, only: [:index]
end

app/models/schedule.rb
# == Schema Information
#
# Table name: schedules
#
#  id          :integer          not null, primary key
#  date        :date
#  time        :time
#  entry_type  :string(255)
#  team_id     :integer
#  created_at  :datetime
#  updated_at  :datetime
#  opponent_id :integer
#

class Schedule < ActiveRecord::Base
  belongs_to :team
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController

  def schedule_manager
    @opponents = current_user.program.opponents
    unless current_user.teams.blank?
      get_appointments
      @appointments = current_user.teams.active.schedules
      @appointments_by_date = @appointments.group_by(&:date)
      @date = params[:date] ? Date.parse(params[:date]) : Date.today
      @team_id = current_user.teams
    end

  end

  def new
    @scheduled_event = Schedule.new
  end

  def create
    @cal_event = Schedule.new()
    num = params[:entry][:event_type]
    set_calendar_event_type(@cal_event, num)
    set_calendar_event_attrs(@cal_event)
    @cal_event.save
    render json: { event: @cal_event}
  end

  def show
    @event = Schedule.find(params[:id])
    @opponent = Opponent.find_by id: @event.opponent_id
    if @opponent.nil?
      return
    else
      @hash = Gmaps4rails.build_markers(@opponent) do |opponent, marker|
        marker.lat opponent.latitude
        marker.lng opponent.longitude
        marker.infowindow "#{opponent.name} #{opponent.address}"
      end
    end
  end


  private

    def set_calendar_event_type(cal_event, num)
      @cal_event = cal_event
      if num == '1'
        @cal_event.entry_type = 'Practice'
      elsif num == '2'
        @cal_event.entry_type = 'Game'
        @cal_event.opponent_id = Opponent.find(params[:entry][:vs]).id #add only if Game selected
      elsif num == '3'
        @cal_event.entry_type = 'Other'
      end
    end

    def set_calendar_event_attrs(cal_event)
      @cal_event = cal_event
      @cal_event.team_id = params[:entry][:id]
      @cal_event.date = params[:entry][:date]
      @cal_event.time = params[:entry][:time]
    end

end

app/helpers/schedule_helper.rb
module ScheduleHelper

  def show_time(time)
    if time.blank?
      time = 'Regular Time'
    else
      time = time.to_time
      time.utc.strftime('%l:%M')
    end
  end

  def show_opponent(event)
    if event.entry_type == "Game"
      o = Opponent.find(event.opponent_id).name
      "vs #{o}"
    else
      return
    end
  end


end

app/views/schedules/_calendar_view.html.haml
#schedule-manager

  %h2#month
    = link_to "<", date: @date.prev_month
    = @date.strftime("%B %Y")
    = link_to ">", date: @date.next_month
  = calendar @date do |date|
    = date.day
    - if @appointments_by_date[date]
      - @appointments_by_date[date].each do |appointment|
        .cal_events
          = link_to appointment.entry_type, appointment
          %span at
          %span= show_time(appointment.time)
          %span= show_opponent(appointment)

app/views/schedules/new.html.haml
%h1 new schedule

app/views/schedules/schedule_manager.html.haml
= render 'layouts/nav_controls'

- if current_user.teams.blank?
  %h1= "There is no team schedule until a"
  %h1= "team is assigned to you."
- else
  %h2 Schedule Manager
  #schedule-controls
    #add-practice.btn.btn-success add Event
    .form-wrapper
      .form-pointer-default
      = form_tag schedules_path, class: 'schedule-forms' do
        / TODO: refactor hidden field tags into method
        = hidden_field_tag(:team_id, current_user.teams.first.id)

        %div
          = label_tag :entry_type, 'Type'
        #entry-type-choice
          = select_tag(:entry_type, options_for_select([ ['PRACTICE', 1, {class: 'entry-options'}], ['GAME', 2, {class: 'entry-options'}] , ['OTHER', 3, {class: 'entry-options'}] ]))
        #opponent-dropdown
          %div
            = label_tag :opponent_id
          %div
            = select_tag(:opponent_id, options_for_select(@opponents.collect{ |opponent| [opponent.name.capitalize, opponent.id, {class: 'division-options'} ]} ))

        %div
          = label_tag :date
        %div
          = text_field_tag :date, nil, id: 'schedule-picker'

        %div
          = label_tag :time
        %div
          = text_field_tag :time, nil, id: 'schedule-time-picker'

        #submit-schedule Add to Calendar


  = render "schedules/calendar_view"

app/views/schedules/show.html.haml
= render 'layouts/nav_controls'
- if @event.entry_type == "Practice"

  %h1
    = "#{@event.entry_type}"
  %h3
    Date:
    = "#{@event.date.strftime('%B %e')}"

  %h3
    Time:
    = "Practice starts at #{show_time(@event.time)}, sharp."


- elsif @event.entry_type == "Game"

  %h1
    = "#{@event.entry_type} Day"

  %section.opponent

    .stat-bar
      %h3
        Date:
        = "#{@event.date.strftime('%B %e')}"
        |
        %span
          Time:
          = "Please arrive by #{show_time(@event.time)}, sharp."

      %h3.stat-bar-title
    = render partial: 'opponents/opponent_information', locals: {opponent: @opponent }