config/routes.rb
FourthAndInches::Application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations" }

  root 'home#index'
  get 'about'     => 'home#about',     as: 'about'
  get 'contact'   => 'home#contact',   as: 'contact'
  get 'dashboard' => 'dashboard#show', as: 'dashboard'
  get 'faq'       => 'home#faq',       as: 'faq'
  get 'features'  => 'home#features',  as: 'features'

  # Access Codes
  post 'send_access_code' => 'access_codes#send_access_code', as: 'send_access_code'
  get 'access/:id' => 'access_codes#verify_access_code', as: 'verify_access_code'

  get 'coaches_corner' => 'coaches#coaches_corner', as: 'coaches_corner'
  get 'office_manager' => 'office#office_manager',

                                                    as: 'office_manager'
  get 'schedule_manager' => 'schedules#schedule_manager',
                                                    as: 'schedule_manager'
  get 'team_manager' => 'teams#team_manager',       as: 'team_manager'
  get 'team_dashboard/:id' => 'teams#team_dashboard', as: 'team_dashboard'

  # post 'opponents/:id/list_destroy' => 'opponents#list_destroy',  as: 'list_destroy'
  post 'programs/set_fee' => 'programs#set_fee'
  post 'programs/:id/ajax_program_edits' => 'programs#ajax_program_edits'

  get "websites/:id" => 'websites#show', as: 'website'
  get 'all_players' => 'websites#all_players'

  resources :users
  resources :coaches,     only: [:new, :create]
  resources :programs,    except: [:edit]
  resources :websites,    only: :create
  resources :charges
  resources :divisions
  resources :opponents do
    member do
      post :list_destroy
    end
  end



  resources :events,      only: [:index]
  resources :schedules,   except: :index
  resources :dashboard,   only: :create
  resources :players
  resources :teams
  resources :sponsors,    only: [:index]
  resources :inventory,   only: [:index]
  resources :merchandise, only: [:index]
end

app/models/player.rb
# == Schema Information
#
# Table name: players
#
#  id                  :integer          not null, primary key
#  first_name          :string(255)
#  last_name           :string(255)
#  address             :string(255)
#  town                :string(255)
#  zip                 :string(255)
#  team_id             :integer
#  parent_id           :integer
#  age                 :integer
#  created_at          :datetime
#  updated_at          :datetime
#  avatar_file_name    :string(255)
#  avatar_content_type :string(255)
#  avatar_file_size    :integer
#  avatar_updated_at   :datetime
#  date_of_birth       :datetime
#  is_registered       :boolean          default(FALSE)
#  program_id          :integer
#

class Player < ActiveRecord::Base
  # has_many :users
  # has_many :users, :through => :teams
  belongs_to :program
  belongs_to :user
  belongs_to :team
  has_one :account

  has_attached_file :avatar, :styles => { :medium => "300x300>",
   :thumb => "100x100>" }, :bucket => 'fourthandinchesmedia',
   :default_url => "/images/:style/missing.png"

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  before_action :find_player, only: [:edit, :update, :show, :destroy]
  after_action :capitalize_name, only: [:create]
  respond_to :html, :js

  def index
    @players = current_user.teams.active.players \
                          unless current_user.user_type == "master"
    all_players = current_user.get_programs_players
    if all_players.empty?
      return
    else
      @all_players = all_players.delete_if { |p| p.first_name == 'cover' }
    end
    find_active_team
  end

  def new
    @player = Player.new
    find_active_team
  end

  def create
    @player = Player.new(player_params)
    unless params[:team_id].blank?
      assign_player_to_team(@player)
    end
    if @player.save
      calculate_age(@player)
      send_to_webpage_or_dashboard(@player)
    else
      render :new
    end
  end

  def edit
    find_active_team
  end

  def update
    @player.update(player_params)
    calculate_age(@player)
    if @player.save
      flash[:notice] = 'player successfully updated'
      redirect_to @player
    else
      render :edit
    end
  end

  def show
    find_player
  end

  def destroy
  end


  private

    def find_player
      @player = Player.find(params[:id])
    end

    def assign_player_to_team(player)
      team = Team.find_by_id(params[:team_id])
      @player.team_id = team.id
      cover = check_for_team_cover(team)
      team.num_of_players.nil? ? team.num_of_players = 1 : team.num_of_players += 1
      team.save
      team.players.unshift(cover)
    end

    def link_player_and_parent(player)
      @player.parent_id = params[:parent_id].to_i
      @player.save
    end

    def send_to_webpage_or_dashboard(player)
     if request.referrer.match(/team_dashboard/)
      link_player_and_parent(player)
      redirect_to :back, :notice => "#{@player.first_name} successfully registered"
     else
      redirect_to team_manager_path, :notice => "player successfully added"
     end
    end

    def find_team
      Team.find(params[:team_id])
    end

    def find_active_team
      @active_team = current_user.teams.first
    end

    def capitalize_name
      @player.last_name = params[:player][:last_name].capitalize
      @player.save
    end

    def check_for_team_cover(team)
      if (team.players[0].first_name == 'cover') && \
         (team.players[0].last_name == 'team_'+ team.id.to_s)
        team.players.shift
      end
    end

    def calculate_age(player)
      bday = player.date_of_birth.to_date
      player.age = (Date.today - bday).to_i / 365
      player.save
    end

    def player_params
      params.require(:player)
              .permit(:first_name, :last_name, :address, :town, :zip, :age,
                      :avatar, :date_of_birth, :is_registered)
    end


end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.haml
.form-pointer-default
= form_for(@player, html: {class: 'default-form-template'}) do |f|
  - unless current_user.user_type == "master"
    = hidden_field_tag(:team_id, @active_team.id)
  .inner-player-form
    .info-section
      %div
        = f.label :first_name
        %br/
        = f.text_field :first_name, autofocus: true

      %div
        = f.label :last_name
        %br/
        = f.text_field :last_name

      %div
        = f.label :address
        %br/
        = f.text_field :address

      %div
        = f.label :town
        %br/
        = f.text_field :town

      %div
        = f.label :zip
        %br/
        = f.text_field :zip

      %div
        = f.label :date_of_birth, 'Date of Birth'
        %br/
        = f.date_select(:date_of_birth, start_year: Date.today.year - 13, end_year: Date.today.year, :order => [:month, :day, :year])


    %div
      = f.submit class: 'default-submit-button'

app/views/players/_player.html.haml
/ User created player form form signed in parent user
= form_for(@player, html: {class: 'general_sign_up_form', id: 'website_channeled_player'}) do |f|
  = hidden_field_tag(:program_id, @team.program.websites.first.id)
  = hidden_field_tag(:parent_id, current_user.id)
  .inner-player-form
    / %p= "Is this the first year with #{@town}? "
    / #player_registered
    /   = f.radio_button :is_registered, "Yes"
    /   = f.label :is_registered, "Yes"
    /   |
    /   = f.radio_button :is_registered, "No"
    /   = f.label :is_registered, "No"
    #new-player
      %div
        = f.label :first_name
        %br/
        = f.text_field :first_name, autofocus: true

      %div
        = f.label :last_name
        %br/
        = f.text_field :last_name

      %div
        = f.label :address
        %br/
        = f.text_field :address

      %div
        = f.label :town
        %br/
        = f.text_field :town

      %div
        = f.label :zip
        %br/
        = f.text_field :zip

      %div
        = f.label :date_of_birth, 'Date of Birth'
        %br/
        = f.date_select(:date_of_birth, start_year: Date.today.year - 13, end_year: Date.today.year, :order => [:month, :day, :year])
      %div
        = f.submit class: 'default-submit-button'

app/views/players/edit.html.haml
%section#on-page-nav
  %nav.inner-nav-links
    = link_to '<< back to team', team_manager_path, class: 'mini-manager-buttons'
#players-edit
  %h3
    = "edit #{@player.first_name}'s profile"

  = render 'players/form'

app/views/players/index.html.haml
%div
  = render 'layouts/nav_controls'


%table.all-players
  #table-header All Players List
  %tr
    %th Photo
    %th First Name
    %th Last Name
    %th Address
    %th Age
    %th Team
  - unless @all_players.blank?
    - @all_players.each do |player|
      %tr
        %td
          = display_mini_player_image(player)
        %td
          = player.first_name
        %td
          = link_to player.last_name, player_path(player)
        %td
          = "#{player.address}, #{player.town}, #{player.zip}"
        %td
          = "#{player.age}"
        %td
          = team_player_belongs_to(player)

app/views/players/new.html.haml
%div
  = render 'layouts/nav_controls'

%h1 Add Player

= render 'players/form'

app/views/players/show.html.haml
= render 'layouts/nav_controls'

.player-card
  .stars-top
    - 5.times do
      %span
        %i.fa.fa-star
  .inner-card
    - if @player.avatar_updated_at.nil?
      Please upload a photo
    = display_player_image(@player)
  .card_info

    .player_name
      .player-banner-stitches-top
        = @player.first_name
        = @player.last_name
      .player-banner-stitches-bottom

    .trading-card-team-banner
      .ribbon
        .ribbon-stitches-top
        %strong.ribbon-content
          %h1= full_team_name
        .ribbon-stitches-bottom
  .stars-bottom
    - 5.times do
      %span
        %i.fa.fa-star

.player-stats
  .player-stat-panel
    .player_name
      .player-banner-stitches-top
        Player Stats
      .player-banner-stitches-bottom
    .name
      = @player.first_name
      = @player.last_name
    .street
      = @player.address
    .town
      = @player.town
      %span , NY
      = @player.zip
    .power-line-separator

    .birth_day
      Born:
      = display_born_on(@player)
      =# @player.date_of_birth.strftime('%B %d, %Y')
    .age
      Age:
      = @player.age
      %br/
      = link_to "edit player info", edit_player_path(@player), class: 'btn btn-warning'


    .photo-section
      = form_for @player, :url => player_path(@player.id), :html => { :multipart => true } do |f|

        .player-avatar-label
          .player_name
            .player-banner-stitches-top
              = f.label :avatar, 'Select Player Image'
            .player-banner-stitches-bottom
          %br/
        %div
          = f.file_field :avatar
        %div
          %br/
          = f.submit "Add Player Image"
        %br/